### ISSUE TITLE
7번의 두 수의 합(Two Sum) 에서 투 포인터로 풀 경우 Wrong Answer가 발생합니다.

### ISSUE THREAD

**Issue by jaeyeonme** [onlybooks/java-algorithm-interview#1]
Case1, 2, 3 중 Case 2번에서 답이 틀리다고 나옵니다!

**Comment by likejazz** [comment]
안녕하세요.

해당 문제 투 포인터 풀이의 경우 책에 왜 풀이가 되지 않는지 상세하게 설명해두었습니다. 책 229페이지를 참고하세요.
감사합니다.

**Comment by jaeyeonme** [comment]
안녕하세요. 

제가 그 다음내용을 안 읽어보고 바로 티켓을 오픈했군요.. ㅜㅜ
감사합니다.
